### ISSUE TITLE
[Bug]: snowflake_authentication_policy no longer working

### ISSUE THREAD

**Issue by mkulisicpecar** [snowflakedb/terraform-provider-snowflake#4093]
### Terraform CLI Version

1.8.5

### Terraform Provider Version

2.8.0

### Company Name

Restaurant Brands International

### Terraform Configuration

```terraform
resource "snowflake_authentication_policy" "ds_service_user_auth_policy" {
  name                   = local.auth_policy_name
  database               = snowflake_database.streaming_db.name
  schema                 = snowflake_schema.policy_schema.name
  mfa_enrollment         = "OPTIONAL"
  authentication_methods = ["KEYPAIR"]
  client_types           = ["SNOWSQL", "DRIVERS"]
}
```

### Category

category:preview

### Expected Behavior

We've so far been using the code shared above to create an auth policy for a service user using keypair auth. This has been working with no issues for the past few months.

### Actual Behavior

Today we noticed that the code above is throwing the following error: 
│ Error: 003639 (01P01): SQL Compilation Error: MFA_AUTHENTICATION_METHODS is deprecated, please use MFA_POLICY=(ENFORCE_MFA_ON_EXTERNAL_AUTHENTICATION=ALL | NONE) instead.
│ 
│   with module.snowflake.snowflake_authentication_policy.ds_service_user_auth_policy,
│   on ../../modules/snowflake/auth_policy.tf line 1, in resource "snowflake_authentication_policy" "ds_service_user_auth_policy":
│    1: resource "snowflake_authentication_policy" "ds_service_user_auth_policy" {

### Steps to Reproduce

Define a snowflake_authenticaiton_policy

### How much impact is this issue causing?

Medium

### Additional Information

Seems related to an underlying change in snowflake that is causing the terraform command to crash. Any resolution steps would be appreciated

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by artisticcheese** [comment]
Same here, was working last week, stopped working today

**Comment by artisticcheese** [comment]
In addition there is new property value available for mfa_enrollment  -> "REQUIRED_SNOWFLAKE_UI_PASSWORD_ONLY" while provider only accepts REQUIRED/OPTIONAL

```
mfa_enrollment             = "REQUIRED_SNOWFLAKE_UI_PASSWORD_ONLY" -> "OPTIONAL"
```

**Comment by sfc-gh-dszmolka** [comment]
possibly related to planned changes contained in [Behaviour Change Bundle 2025_06](https://docs.snowflake.com/en/release-notes/bcr-bundles/2025_06_bundle) rolled out this week. 
> Status planned to change in the 9.32 release (October 13-15, 2025) to Enabled by Default;

* [Pre-announcement on the change](https://community.snowflake.com/s/article/Upcoming-MFA-enforcement-for-Snowsight-logins) on Snowflake knowledge article.
* [announcement on BCR 2025_06 related changes here in this repo](https://github.com/snowflakedb/terraform-provider-snowflake/blob/5f587a2de30186c90021826304851645b74bc2ec/SNOWFLAKE_BCR_MIGRATION_GUIDE.md#bundle-2025_06)

Simple check if related or not, is to [disable the bundle](https://docs.snowflake.com/en/sql-reference/functions/system_disable_behavior_change_bundle) (login to Snowflake GUI or issue the following SQL statement in another manner)
```
SELECT SYSTEM$DISABLE_BEHAVIOR_CHANGE_BUNDLE('2025_06');
```

and if it again immediately starts working again, its related.

Please if possible, read the bundle contents in the above link. Since with Snowflake v9.32 the bundle became opt-out (enabled by default, can be opted out still), it gives around ~4 weeks of opt-out  time before it becomes part of Snowflake and no longer opt-out-able (if there's such a word)

edit: re the options; checked [MfaEnrollmentOption](https://github.com/snowflakedb/terraform-provider-snowflake/blob/v2.8.0/pkg/sdk/authentication_policies_def.go#L46-L50) and it looks like there's 3 options in SF TF Provider v2.8.0
```go
const (
	MfaEnrollmentRequired             MfaEnrollmentOption = "REQUIRED"
	MfaEnrollmentRequiredPasswordOnly MfaEnrollmentOption = "REQUIRED_PASSWORD_ONLY"
	MfaEnrollmentOptional             MfaEnrollmentOption = "OPTIONAL"
)
```

the middle one wasn't available in v2.7.0 or before, but I also see that we did announce
> Additionally, the allowed values for MFA_ENROLLMENT are changed: OPTIONAL is removed and REQUIRED_PASSWORD_ONLY and REQUIRED_SNOWFLAKE_UI_PASSWORD_ONLY are added.

yet the `REQUIRED_SNOWFLAKE_UI_PASSWORD_ONLY` option is not available so we probably need to add that.

**Comment by sfc-gh-jmichalak** [comment]
Hi @mkulisicpecar 👋 

I'm currently working on this. We'll improve the authentication policies with the updated syntax. For now, please
1. Disable the 2025_06 bundle.
2. Remove the `mfa_authentication_methods` from the configuration.
3. Enable the 2025_06 bundle.
4. If you get a non-empty plan on the `mfa_authentication_methods` (it's still in the state), use the [ignore_changes](https://developer.hashicorp.com/terraform/language/meta-arguments) attribute.

**Comment by afzanjamalreach** [comment]
@sfc-gh-jmichalak do you think this can be included as part of the improvements you're working on?
https://github.com/snowflakedb/terraform-provider-snowflake/issues/3674

**Comment by sfc-gh-jmichalak** [comment]
Hi @afzanjamalreach 👋 

Yes, this request (and other feature gaps) will also be included.

**Comment by sfc-gh-jmichalak** [comment]
Hi,

We released v2.10.0 ([release notes](https://github.com/snowflakedb/terraform-provider-snowflake/releases/tag/v2.10.0), [migration guide](https://github.com/snowflakedb/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md#v29x--v2100)). In this version, we reworked this resource, and added missing features. Enjoy!

**Comment by ppo-corp** [comment]
Hi @sfc-gh-jmichalak, I've just tried the resource with the latest provider version v2.10.0 and I have this error :

`Error: invalid MFA enrollment option: REQUIRED_SNOWFLAKE_UI_PASSWORD_ONLY`

I tried to comment the `mfa_enrollment` attribute and add this lifecycle `lifecycle { ignore_changes = [ mfa_enrollment ] }` in the resource but still have the issue. Any idea ?

**Comment by sfc-gh-jmichalak** [comment]
Hi, 

This error is happening during handling the DESC output. The provider is currently not doing it correctly, and I'm currently working on a fix. We should be able to release the fixed version soon.

As a workaround, you may consider setting the `REQUIRED` or `REQUIRED_PASSWORD_ONLY` options, but we are aware that it may disrupt authentication flows, so try on a testing environment first.

**Comment by heathermrauch** [comment]
I was trying to remediate a critical alert I was receiving from the trust center despite having an authentication policy set that requires MFA. I dropped and tried to recreate it but am now getting the error "invalid property 'MFA_AUTHENTICATION_METHODS' for 'AUTHENTICATION_POLICY'. It is unclear from this thread what I need to do to recreate my authentication policy. Am I just stuck not having one until Snowflake figures out how to fix this?

**Comment by sfc-gh-asawicki** [comment]
@heathermrauch, please check this section: https://github.com/snowflakedb/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md#handling-deprecated-mfa_authentication_methods-field.

**Comment by jrobison-sb** [comment]
> Hi,
> 
> This error is happening during handling the DESC output. The provider is currently not doing it correctly, and I'm currently working on a fix. We should be able to release the fixed version soon.
> 
> As a workaround, you may consider setting the `REQUIRED` or `REQUIRED_PASSWORD_ONLY` options, but we are aware that it may disrupt authentication flows, so try on a testing environment first.

Hi @sfc-gh-jmichalak, we ran into a similar problem when testing dependabot's PR to upgrade to 2.10.0. Our use case is probably the same thing as what you are working on, but just in case it's not, I'll describe it here.

On 2.8.0, this resource works fine. No `terraform plan` permadiffs, no deprecation warnings, etc.
```
resource "snowflake_authentication_policy" "account_level" {
  database = snowflake_database.authentication_policy.name
  schema   = snowflake_schema.authentication_policy.name
  name     = "${upper(var.env_name)}_ACCOUNT_LEVEL"
  mfa_authentication_methods = ["SAML", "PASSWORD"]

  lifecycle {
    ignore_changes = [
      mfa_enrollment,
    ]
  }
}
```

Note that we do have `mfa_enrollment = "REQUIRED_SNOWFLAKE_UI_PASSWORD_ONLY"` in the state, even though it's not directly specified in the HCL.

Upon testing an upgrade to 2.10.0, we get this:
```
│ Warning: Argument is deprecated
│ 
│   with module.production_application.snowflake_authentication_policy.account_level,
│   on ../../modules/aws/application/snowflake.tf line 1668, in resource "snowflake_authentication_policy" "account_level":
│ 1668:   mfa_authentication_methods = ["SAML", "PASSWORD"]
│ 
│ This field is deprecated and will be removed in the future. The new field
│ `ENFORCE_MFA_ON_EXTERNAL_AUTHENTICATION` will be added in the next versions
│ of the provider. Read our [BCR Migration
│ Guide](https://github.com/snowflakedb/terraform-provider-snowflake/blob/main/SNOWFLAKE_BCR_MIGRATION_GUIDE.md#changes-in-authentication-policies)
│ for more migration steps and more details.
╵
╷
│ Error: invalid MFA enrollment option: REQUIRED_SNOWFLAKE_UI_PASSWORD_ONLY
│ 
│   with module.production_application.snowflake_authentication_policy.account_level,
│   on ../../modules/aws/application/snowflake.tf line 1664, in resource "snowflake_authentication_policy" "account_level":
│ 1664: resource "snowflake_authentication_policy" "account_level" {
```

The `mfa_authentication_methods = ["SAML", "PASSWORD"]` deprecation warning goes away if we delete or comment that line, so that one's easy.

But the `invalid MFA enrollment option: REQUIRED_SNOWFLAKE_UI_PASSWORD_ONLY` error doesn't go away, even though we don't directly specify this option anywhere in our HCL. Presumably the presence of `mfa_enrollment = "REQUIRED_SNOWFLAKE_UI_PASSWORD_ONLY"` in the state is causing `terraform plan` to choke.

**Comment by jreslock** [comment]
> > Hi,
> > This error is happening during handling the DESC output. The provider is currently not doing it correctly, and I'm currently working on a fix. We should be able to release the fixed version soon.
> > As a workaround, you may consider setting the `REQUIRED` or `REQUIRED_PASSWORD_ONLY` options, but we are aware that it may disrupt authentication flows, so try on a testing environment first.
> 
> Hi [@sfc-gh-jmichalak](https://github.com/sfc-gh-jmichalak), we ran into a similar problem when testing dependabot's PR to upgrade to 2.10.0. Our use case is probably the same thing as what you are working on, but just in case it's not, I'll describe it here.
> 
> On 2.8.0, this resource works fine. No `terraform plan` permadiffs, no deprecation warnings, etc.
> 
> ```
> resource "snowflake_authentication_policy" "account_level" {
>   database = snowflake_database.authentication_policy.name
>   schema   = snowflake_schema.authentication_policy.name
>   name     = "${upper(var.env_name)}_ACCOUNT_LEVEL"
>   mfa_authentication_methods = ["SAML", "PASSWORD"]
> 
>   lifecycle {
>     ignore_changes = [
>       mfa_enrollment,
>     ]
>   }
> }
> ```
> 
> Note that we do have `mfa_enrollment = "REQUIRED_SNOWFLAKE_UI_PASSWORD_ONLY"` in the state, even though it's not directly specified in the HCL.
> 
> Upon testing an upgrade to 2.10.0, we get this:
> 
> ```
> │ Warning: Argument is deprecated
> │ 
> │   with module.production_application.snowflake_authentication_policy.account_level,
> │   on ../../modules/aws/application/snowflake.tf line 1668, in resource "snowflake_authentication_policy" "account_level":
> │ 1668:   mfa_authentication_methods = ["SAML", "PASSWORD"]
> │ 
> │ This field is deprecated and will be removed in the future. The new field
> │ `ENFORCE_MFA_ON_EXTERNAL_AUTHENTICATION` will be added in the next versions
> │ of the provider. Read our [BCR Migration
> │ Guide](https://github.com/snowflakedb/terraform-provider-snowflake/blob/main/SNOWFLAKE_BCR_MIGRATION_GUIDE.md#changes-in-authentication-policies)
> │ for more migration steps and more details.
> ╵
> ╷
> │ Error: invalid MFA enrollment option: REQUIRED_SNOWFLAKE_UI_PASSWORD_ONLY
> │ 
> │   with module.production_application.snowflake_authentication_policy.account_level,
> │   on ../../modules/aws/application/snowflake.tf line 1664, in resource "snowflake_authentication_policy" "account_level":
> │ 1664: resource "snowflake_authentication_policy" "account_level" {
> ```
> 
> The `mfa_authentication_methods = ["SAML", "PASSWORD"]` deprecation warning goes away if we delete or comment that line, so that one's easy.
> 
> But the `invalid MFA enrollment option: REQUIRED_SNOWFLAKE_UI_PASSWORD_ONLY` error doesn't go away, even though we don't directly specify this option anywhere in our HCL. Presumably the presence of `mfa_enrollment = "REQUIRED_SNOWFLAKE_UI_PASSWORD_ONLY"` in the state is causing `terraform plan` to choke.

Can confirm I am experiencing this same behavior using 2.10.0. I noticed if I run the following in Snowflake directly I see the same value persist despite the fact that I explicitly set it to `OPTIONAL`

```
DESC AUTHENTICATION POLICY DB.SCHEMA.<redacted>;

It shows me
MFA_ENROLLMENT = REQUIRED_SNOWFLAKE_UI_PASSWORD_ONLY

The description for this property IN THE DESCRIBE OUTPUT states:
"When set to REQUIRED, force a user to enroll in MFA according to the MFA_AUTHENTICATION_METHODS. Allowed values are REQUIRED | OPTIONAL"

I execute:
ALTER AUTHENTICATION POLICY DB.NAME.<redacted> SET MFA_ENROLLMENT = "OPTIONAL";

(successful)

DESC AUTHENTICATION POLICY DB.SCHEMA.<redacted>;

It shows me, once again:
MFA_ENROLLMENT = REQUIRED_SNOWFLAKE_UI_PASSWORD_ONLY
```

This is being set/enforced automatically in Snowflake to a value that does not match the property description at all. I am unsure if this is _only_ a provider issue given that I can reproduce the causal behavior directly in Snowsight. The fact that plan fails is certainly a provider issue but the unexpected return value from the API is the real problem.

**Comment by sfc-gh-jmichalak** [comment]
Hi,

We released v2.10.1 ([release notes](https://github.com/snowflakedb/terraform-provider-snowflake/releases/tag/v2.10.1), [migration guide](https://github.com/snowflakedb/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md#v2100--v2101)). In this version, we allowed the REQUIRED_SNOWFLAKE_UI_PASSWORD_ONLY value in the SDK, which should resolve the issue. Enjoy!

@jreslock, the provider simply passes the values from the SHOW output in Snowflake. I think it's a matter of your account setup. If you'd like to reconfigure you authentication setup, please reach out to your account manager or support.

**Comment by ppo-corp** [comment]
Fixed ! Thanks @sfc-gh-jmichalak for your reactivity !

**Comment by jreslock** [comment]
> Hi,
> 
> We released v2.10.1 ([release notes](https://github.com/snowflakedb/terraform-provider-snowflake/releases/tag/v2.10.1), [migration guide](https://github.com/snowflakedb/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md#v2100--v2101)). In this version, we allowed the REQUIRED_SNOWFLAKE_UI_PASSWORD_ONLY value in the SDK, which should resolve the issue. Enjoy!
> 
> [@jreslock](https://github.com/jreslock), the provider simply passes the values from the SHOW output in Snowflake. I think it's a matter of your account setup. If you'd like to reconfigure you authentication setup, please reach out to your account manager or support.

@sfc-gh-jmichalak thank you for the new release. I can confirm that I am no longer experiencing this issue with version 2.10.1 of the provider.

**Comment by sfc-gh-jmichalak** [comment]
Closing due to inactivity.
